language: node_js
node_js: 
  - node
  
dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - icysloth@yahoo.com.sg
    on_success: always
    on_failure: always

branches:
  only:
   - master

before_script:
  - npm install -g @angular/cli
  - npm audit fix
  
script:
  - ng lint
  - ng build --prod --base-href https://icysloth.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  on: 
   branch: master
